### ISSUE TITLE
Question: What firmware are you running

### ISSUE THREAD

**Issue by ithinkido** [MarkJB/esp32-stepper-board#1]
HI Mark,

I was looking for some ideas today for a  plotter and came across you PCB. Any chance you tell me what firmware you are running on this board?

Thanks

**Comment by MarkJB** [comment]
There isn't any firmware for this board yet. It was meant to be a development board to enable members of a local maker space to write the firmware but we never got round to it.

It may be possible to run an ESP32 port of GRBL but I haven't tried it.

**Comment by ithinkido** [comment]
Ok, thanks. 
A pitty,it is  a nice looking design.
